### ISSUE TITLE
Integration with app issues

### ISSUE THREAD

**Issue by mark-cooper** [collectionspace/collectionspace-mapper#76]
The `ruby-prof` gem is a development dependency:

https://github.com/collectionspace/collectionspace-mapper/blob/master/collectionspace-mapper.gemspec#L45

However the way it is required results in it failing when installed in a context that doesn't pull in those dependencies:

https://github.com/collectionspace/collectionspace-mapper/blob/master/lib/collectionspace/mapper.rb#L14

```txt
... `require': cannot load such file -- ruby-prof (LoadError)
... collectionspace-mapper-1aabbc165de7/lib/collectionspace/mapper.rb:14:in `<main>'
```

There is a workaround -- to make `ruby-prof` a dependency in the app -- but I'd prefer to avoid that. Maybe you can switch to cli usage?

---

Don't export aliases into the global namespace, for example:

https://github.com/collectionspace/collectionspace-mapper/blob/master/lib/collectionspace/mapper.rb#L18

We did this for the old converter, but that was pretty much a sandbox, This is clashing with an AR model also called `Mapper` 😄

Because most of your stuff is within the same module (`CollectionSpace::Mapper`) it looks like you won't have to update too much (maybe just `CollectionSpace::Mapper.setup_data(data)`?).

**Comment by kspurgin** [comment]
@mark-cooper -- I believe both of these are now resolved
